package com.lyrebird.rc.server

import com.lyrebird.rc.StreamingMode
import com.lyrebird.rc.settings.DroneSettingsProfilesTest
import com.lyrebird.rc.settings.LyrebirdSettings
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * The publisher's configuration, answered without a screen.
 *
 * This is what used to come from the Flight Deck's own callbacks, so the streamer could not even
 * be composed while no activity was attached. Everything here has to hold with nothing but a
 * preference store and the aircraft's serial — and the name has to be the one the rest of the app
 * publishes under, because the dashboard builds its WHEP URL from it: a second derivation rule
 * here would send a ground station to a path nothing publishes to.
 */
class V5StreamingSettingsTest {
    private val serial = "1581F6Z9C238Q0033XR2"

    private fun settings(
        prefs: Map<String, Any> = emptyMap(),
        aircraftSerial: String = serial,
    ): Pair<V5StreamingSettings, DroneSettingsProfilesTest.FakePrefs> {
        val preferences = DroneSettingsProfilesTest.FakePrefs(prefs)
        return V5StreamingSettings(preferences) { aircraftSerial } to preferences
    }

    @Test
    fun `the operator's name is what the aircraft publishes and consumes under`() {
        val (underTest, _) = settings(mapOf(LyrebirdSettings.PREF_DRONE_NAME to "mini1"))

        assertEquals("mini1", underTest.droneName)
        assertEquals("http://10.9.0.5:8889/mini1/whip", underTest.whipUrl("10.9.0.5"))
    }

    @Test
    fun `with no name stored, the serial decides by the shared rule`() {
        val (underTest, _) = settings()

        assertEquals(LyrebirdSettings.deriveDroneName(serial), underTest.droneName)
        assertEquals("lb_q0033xr2", underTest.droneName)
    }

    @Test
    fun `a configured MediaMTX server is where the publisher publishes`() {
        val (underTest, _) =
            settings(
                mapOf(
                    LyrebirdSettings.PREF_DRONE_NAME to "mini1",
                    LyrebirdSettings.PREF_MEDIAMTX_SERVER to "ws://10.9.0.7:8889",
                ),
            )

        assertEquals("ws://10.9.0.7:8889", underTest.configuredServer())
        // The scheme is normalised to the endpoint's own form (WhipEndpoint): the configured
        // server decides the host and port, never the URL text.
        assertEquals("http://10.9.0.7:8889/mini1/whip", underTest.whipUrl("10.9.0.5"))
    }

    @Test
    fun `forgetting a wrong MediaMTX server clears only that preference`() {
        val (underTest, preferences) =
            settings(
                mapOf(
                    LyrebirdSettings.PREF_MEDIAMTX_SERVER to "ws://stale.example:8889",
                    LyrebirdSettings.PREF_DRONE_NAME to "mini1",
                ),
            )

        underTest.clearConfiguredServer()

        assertEquals("", underTest.configuredServer())
        assertEquals("the aircraft's name is not the server preference's business", "mini1", underTest.droneName)
        assertTrue(preferences.contains(LyrebirdSettings.PREF_DRONE_NAME))
    }

    @Test
    fun `the mode and the media options are the settings file's, not a screen's`() {
        val (underTest, _) =
            settings(
                mapOf(
                    LyrebirdSettings.PREF_STREAMING_MODE to StreamingMode.RTMP.prefValue,
                    LyrebirdSettings.PREF_WEBRTC_FPS to 15,
                ),
            )

        assertEquals(StreamingMode.RTMP, underTest.mode)
        assertEquals(15, underTest.options.fps)
    }

    @Test
    fun `an autogenerated name is url-safe`() {
        val (underTest, _) = settings(aircraftSerial = "not a serial!")

        assertEquals("lb__serial_", underTest.droneName)
        assertFalse("the name becomes a URL path", underTest.droneName.contains(" "))
    }
}

